"""Scan ``loopx/`` for every carrier of a closed-set vocabulary.

The inventory is the repository-wide map behind the curated registry. It is
generated by ``scripts/generate_semantic_inventory.py`` and checked for
freshness by the drift smoke, so a PR that adds an enum, a ``Literal`` alias, a
TypeScript ``as const`` array, a named closed set, or a schema-version constant
shows that addition in a reviewable JSON diff. Nothing here is imported by
product code.
"""

from __future__ import annotations

import ast
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
import re
from typing import Any

INVENTORY_SCHEMA_VERSION = "loopx_semantic_inventory_v0"
DEFAULT_ROOT = "loopx"
SOURCE_SUFFIXES = (".py", ".ts")
SKIP_PARTS = frozenset({"__pycache__", "node_modules"})

UPPER_NAME = re.compile(r"^[A-Z][A-Z0-9_]*$")
SCHEMA_VERSION_NAME = re.compile(r"SCHEMA_VERSION$")
TS_CONST_ARRAY = re.compile(
    r"^export const (?P<name>[A-Z][A-Z0-9_]*)\s*(?::[^=\n]+)?=\s*\[(?P<body>.*?)\]\s*as const;",
    re.MULTILINE | re.DOTALL,
)
TS_STRING_CONST = re.compile(
    r"^export const (?P<name>[A-Z][A-Z0-9_]*)\s*(?::\s*string)?\s*=\s*\"(?P<value>[^\"]*)\";",
    re.MULTILINE,
)
QUOTED = re.compile(r"\"([^\"]*)\"")


@dataclass(frozen=True)
class SourceFile:
    path: str
    suffix: str
    text: str


def load_sources(repo_root: Path, root: str = DEFAULT_ROOT) -> list[SourceFile]:
    files: list[SourceFile] = []
    for path in sorted((repo_root / root).rglob("*")):
        if not path.is_file() or path.suffix not in SOURCE_SUFFIXES:
            continue
        if SKIP_PARTS.intersection(path.parts):
            continue
        files.append(
            SourceFile(
                path=str(path.relative_to(repo_root)),
                suffix=path.suffix,
                text=path.read_text(encoding="utf-8", errors="replace"),
            )
        )
    return files


def _is_enum_class(node: ast.ClassDef) -> bool:
    for base in node.bases:
        name = base.id if isinstance(base, ast.Name) else getattr(base, "attr", "")
        if name.endswith("Enum"):
            return True
    return False


def _string_elements(node: ast.AST) -> list[str] | None:
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
        if node.func.id in {"frozenset", "set", "tuple", "list"} and len(node.args) == 1:
            return _string_elements(node.args[0])
        return None
    if isinstance(node, (ast.Tuple, ast.Set, ast.List)):
        values: list[str] = []
        for element in node.elts:
            if not isinstance(element, ast.Constant) or not isinstance(element.value, str):
                return None
            values.append(element.value)
        return values
    return None


def _container_name(node: ast.AST) -> str:
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
        return node.func.id
    return type(node).__name__.lower()


def _assigned_name(node: ast.AST) -> tuple[str, ast.AST] | None:
    if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
        return node.targets[0].id, node.value
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.value is not None:
        return node.target.id, node.value
    return None


def python_facts(source: SourceFile) -> dict[str, list[dict[str, Any]]]:
    facts: dict[str, list[dict[str, Any]]] = {
        "enums": [],
        "closed_sets": [],
        "literal_aliases": [],
        "string_constants": [],
    }
    try:
        tree = ast.parse(source.text)
    except SyntaxError:
        return facts
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and _is_enum_class(node):
            values: list[str] = []
            string_valued = True
            for item in node.body:
                assigned = _assigned_name(item)
                if assigned is None:
                    continue
                name, value = assigned
                if name.startswith("_"):
                    continue
                if isinstance(value, ast.Constant) and isinstance(value.value, str):
                    values.append(value.value)
                else:
                    string_valued = False
            if values and string_valued:
                facts["enums"].append({"name": node.name, "module": source.path, "values": values})
            continue
        assigned = _assigned_name(node)
        if assigned is None:
            continue
        name, value = assigned
        if isinstance(value, ast.Subscript) and isinstance(value.value, ast.Name) and value.value.id == "Literal":
            elements = _string_elements(value.slice) if isinstance(value.slice, ast.Tuple) else None
            if elements is None and isinstance(value.slice, ast.Constant) and isinstance(value.slice.value, str):
                elements = [value.slice.value]
            if elements:
                facts["literal_aliases"].append({"name": name, "module": source.path, "values": elements})
            continue
        if not UPPER_NAME.match(name):
            continue
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            facts["string_constants"].append({"name": name, "module": source.path, "value": value.value})
            continue
        elements = _string_elements(value)
        if elements is not None and len(elements) >= 2:
            facts["closed_sets"].append(
                {
                    "name": name,
                    "module": source.path,
                    "container": _container_name(value),
                    "values": elements,
                }
            )
    return facts


def typescript_facts(source: SourceFile) -> dict[str, list[dict[str, Any]]]:
    facts: dict[str, list[dict[str, Any]]] = {"const_arrays": [], "string_constants": []}
    for match in TS_CONST_ARRAY.finditer(source.text):
        values = QUOTED.findall(match.group("body"))
        if values:
            facts["const_arrays"].append(
                {"name": match.group("name"), "module": source.path, "values": values}
            )
    for match in TS_STRING_CONST.finditer(source.text):
        facts["string_constants"].append(
            {"name": match.group("name"), "module": source.path, "value": match.group("value")}
        )
    return facts


def _duplicate_kind(modules: list[str]) -> str:
    """One .py plus one .ts definition is a runtime twin; anything else is a fork."""
    suffixes = sorted(Path(module).suffix for module in modules)
    return "cross_runtime_twin" if suffixes == [".py", ".ts"] else "same_runtime_fork"


def _sorted_entries(entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(entries, key=lambda entry: (entry["module"], entry["name"]))


def build_inventory(
    repo_root: Path, root: str = DEFAULT_ROOT, sources: list[SourceFile] | None = None
) -> dict[str, Any]:
    if sources is None:
        sources = load_sources(repo_root, root)
    enums: list[dict[str, Any]] = []
    closed_sets: list[dict[str, Any]] = []
    literal_aliases: list[dict[str, Any]] = []
    const_arrays: list[dict[str, Any]] = []
    string_constants: list[dict[str, Any]] = []
    for source in sources:
        if source.suffix == ".py":
            facts = python_facts(source)
            enums.extend(facts["enums"])
            closed_sets.extend(facts["closed_sets"])
            literal_aliases.extend(facts["literal_aliases"])
            string_constants.extend(facts["string_constants"])
        else:
            facts = typescript_facts(source)
            const_arrays.extend(facts["const_arrays"])
            string_constants.extend(facts["string_constants"])

    definitions = string_constant_definitions(string_constants)
    twins: list[dict[str, Any]] = []
    forks: list[dict[str, Any]] = []
    conflicting: list[dict[str, Any]] = []
    for name, defs in sorted(definitions.items()):
        if len(defs) < 2:
            continue
        modules = [item["module"] for item in defs]
        entry: dict[str, Any] = {"name": name, "is_schema_version": bool(SCHEMA_VERSION_NAME.search(name))}
        if len({item["value"] for item in defs}) == 1:
            entry.update({"value": defs[0]["value"], "modules": modules})
            (twins if _duplicate_kind(modules) == "cross_runtime_twin" else forks).append(entry)
        else:
            entry["definitions"] = defs
            conflicting.append(entry)

    return {
        "schema_version": INVENTORY_SCHEMA_VERSION,
        "root": root,
        "generator": "scripts/generate_semantic_inventory.py",
        "advisory": (
            "Structural map only. Consumer counts are printed by the generator's --report "
            "and are not committed. Single-module string constants are counted, not listed."
        ),
        "python_enums": _sorted_entries(enums),
        "python_closed_sets": _sorted_entries(closed_sets),
        "python_literal_aliases": _sorted_entries(literal_aliases),
        "typescript_const_arrays": _sorted_entries(const_arrays),
        "duplicate_definitions": {
            "cross_runtime_twins": twins,
            "same_runtime_forks": forks,
            "conflicting_values": conflicting,
        },
        "summary": {
            "source_files": len(sources),
            "python_enums": len(enums),
            "python_closed_sets": len(closed_sets),
            "python_literal_aliases": len(literal_aliases),
            "typescript_const_arrays": len(const_arrays),
            "named_string_constants": len(string_constants),
            "schema_version_names": sum(1 for name in definitions if SCHEMA_VERSION_NAME.search(name)),
            "schema_version_same_runtime_forks": sum(1 for item in forks if item["is_schema_version"]),
            "cross_runtime_twins": len(twins),
            "same_runtime_forks": len(forks),
            "same_runtime_fork_definitions": sum(len(item["modules"]) for item in forks),
            "conflicting_values": len(conflicting),
            "conflicting_definitions": sum(len(item["definitions"]) for item in conflicting),
        },
    }


def string_constant_definitions(string_constants: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Group ``NAME = "value"`` definitions by constant name, modules sorted."""
    by_name: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for entry in string_constants:
        by_name[entry["name"]].append({"module": entry["module"], "value": entry["value"]})
    return {name: sorted(defs, key=lambda item: item["module"]) for name, defs in by_name.items()}


def collect_string_constants(sources: list[SourceFile]) -> list[dict[str, Any]]:
    constants: list[dict[str, Any]] = []
    for source in sources:
        facts = python_facts(source) if source.suffix == ".py" else typescript_facts(source)
        constants.extend(facts["string_constants"])
    return constants


def render_inventory(inventory: dict[str, Any]) -> str:
    """Two-space indented JSON with one line per inventory entry for readable diffs."""
    import json

    def one_line(value: Any) -> str:
        return json.dumps(value, ensure_ascii=False, separators=(", ", ": "))

    lines = ["{"]
    keys = list(inventory)
    for index, key in enumerate(keys):
        value = inventory[key]
        comma = "," if index < len(keys) - 1 else ""
        if isinstance(value, list):
            if not value:
                lines.append(f'  "{key}": []{comma}')
                continue
            lines.append(f'  "{key}": [')
            for position, entry in enumerate(value):
                lines.append("    " + one_line(entry) + ("," if position < len(value) - 1 else ""))
            lines.append(f"  ]{comma}")
        elif isinstance(value, dict) and value and all(isinstance(item, list) for item in value.values()):
            lines.append(f'  "{key}": {{')
            inner_keys = list(value)
            for inner_index, inner_key in enumerate(inner_keys):
                entries = value[inner_key]
                inner_comma = "," if inner_index < len(inner_keys) - 1 else ""
                if not entries:
                    lines.append(f'    "{inner_key}": []{inner_comma}')
                    continue
                lines.append(f'    "{inner_key}": [')
                for position, entry in enumerate(entries):
                    lines.append("      " + one_line(entry) + ("," if position < len(entries) - 1 else ""))
                lines.append(f"    ]{inner_comma}")
            lines.append(f"  }}{comma}")
        else:
            rendered = json.dumps(value, ensure_ascii=False, indent=2)
            rendered = "\n".join(("  " + line) if i else line for i, line in enumerate(rendered.splitlines()))
            lines.append(f'  "{key}": {rendered}{comma}')
    lines.append("}")
    return "\n".join(lines) + "\n"


def consumer_ranking(inventory: dict[str, Any], sources: list[SourceFile]) -> list[dict[str, Any]]:
    """Advisory ranking: modules outside the definer that mention each symbol.

    Not stored in the committed inventory because it changes with every consumer
    edit; the generator prints it on demand so retirement work can be ordered.
    """
    ranking: list[dict[str, Any]] = []
    for section in ("python_enums", "typescript_const_arrays", "python_closed_sets", "python_literal_aliases"):
        for entry in inventory[section]:
            token = re.compile(rf"\b{re.escape(entry['name'])}\b")
            consumers = sum(
                1 for source in sources if source.path != entry["module"] and token.search(source.text)
            )
            ranking.append(
                {
                    "kind": section,
                    "name": entry["name"],
                    "module": entry["module"],
                    "values": len(entry["values"]),
                    "external_consumer_modules": consumers,
                }
            )
    return sorted(ranking, key=lambda item: (-item["external_consumer_modules"], item["module"], item["name"]))
